project_id = "kgtbciqqvctjrelgbdvx"

[functions.upsert-chatter-live]
verify_jwt = false

[functions.backfill-incoming-stats]
verify_jwt = false

[functions.pull-chatter-live]
verify_jwt = false

[functions.chats-webhook]
verify_jwt = false
