// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-live-status.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.101.1";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function textResult(value) {
  return { content: [{ type: "text", text: JSON.stringify(value) }] };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}

// src/lib/mcp/tools/get-live-status.ts
var get_live_status_default = defineTool({
  name: "get_live_status",
  title: "Echtzeit-Status der Chatter",
  description: "Echtzeit-Daten pro Chatter: offene Chats, \xE4ltester unbeantworteter Chat (Verzug in Tagen), Umsatz heute, Mass-DMs, plus Aufschl\xFCsselung pro Model/Account. Nutze das f\xFCr Fragen zu Verzug, offenen Chats und aktueller Auslastung. Verzug z\xE4hlt erst ab 3 Tagen.",
  inputSchema: {
    platform: z.string().describe("Plattform, z.B. 'Maloum' oder 'Brezzels'."),
    chatter_name: z.string().nullable().describe("Optionaler Chatter-Filter (Teilstring)."),
    min_delay_days: z.number().nullable().describe("Nur Chatter mit \xE4ltestem Chat >= N Tage."),
    sort: z.enum(["delay", "unread", "revenue"]).nullable().describe("Sortierung, Default 'delay'."),
    limit: z.number().nullable().describe("Max. Anzahl Zeilen, Default 40.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ platform, chatter_name, min_delay_days, sort, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    let q = supabaseForUser(ctx).from("chatter_history_live").select("chatter_name,unread_chats,oldest_chat,revenue,mass_dms,stats_details,updated_at").ilike("platform", platform);
    if (chatter_name) q = q.ilike("chatter_name", `%${chatter_name}%`);
    if (typeof min_delay_days === "number") q = q.gte("oldest_chat", min_delay_days);
    const col = sort === "unread" ? "unread_chats" : sort === "revenue" ? "revenue" : "oldest_chat";
    const { data, error } = await q.order(col, { ascending: false, nullsFirst: false }).limit(Math.min(limit ?? 40, 200));
    if (error) return errorResult(error.message);
    return textResult({ count: data?.length ?? 0, rows: data });
  }
});

// src/lib/mcp/tools/get-chatter-history.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";

// src/lib/mcp/tools/active-roster.ts
function normalizeName(name) {
  return name.normalize("NFKC").replace(/[\uFE00-\uFE0F\u200B-\u200F\u202A-\u202E\u2060-\u206F\uFEFF\u00AD]/g, "").replace(/[\u00A0\u2007\u202F]/g, " ").toLowerCase().replace(/[_ ]+/g, "_").trim();
}
async function loadActiveChatterNames(supabase, platform) {
  const { data: reports } = await supabase.from("analysis_reports").select("result_json, analysis_date").eq("platform", platform).not("result_json", "is", null).order("analysis_date", { ascending: false }).order("created_at", { ascending: false }).limit(1);
  const latest = reports?.[0];
  if (!latest) return null;
  const names = /* @__PURE__ */ new Set();
  const result = latest.result_json;
  if (result && Array.isArray(result.categories)) {
    for (const cat of result.categories) {
      for (const ch of cat.chatters ?? []) {
        if (ch?.name) names.add(normalizeName(ch.name));
      }
    }
  }
  if (names.size === 0 && latest.analysis_date) {
    const { data: histRows } = await supabase.from("chatter_history").select("chatter_name").eq("platform", platform).eq("analysis_date", latest.analysis_date);
    for (const r of histRows ?? []) {
      if (r.chatter_name) names.add(normalizeName(r.chatter_name));
    }
  }
  return names;
}

// src/lib/mcp/tools/get-chatter-history.ts
var get_chatter_history_default = defineTool2({
  name: "get_chatter_history",
  title: "Chatter-Verlauf",
  description: "Tages-Zeitreihe eines aktuellen Chatters: Umsatz, Mass-DMs, offene Chats, Verzug, Account und Kategorie pro Tag. F\xFCr Trend- und Verlaufsfragen zu einer konkreten Person. Nur Chatter aus dem letzten Report.",
  inputSchema: {
    platform: z2.string().describe("Plattform, z.B. 'Maloum'."),
    chatter_name: z2.string().describe("Name des Chatters (Teilstring reicht)."),
    days: z2.number().nullable().describe("Zeitfenster in Tagen, Default 30.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ platform, chatter_name, days }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const win = Math.min(days ?? 30, 365);
    const from = /* @__PURE__ */ new Date();
    from.setDate(from.getDate() - win);
    const supabase = supabaseForUser(ctx);
    const activeNames = await loadActiveChatterNames(supabase, platform);
    const { data, error } = await supabase.from("chatter_history").select("chatter_name,analysis_date,account,revenue_today,mass_dms,open_chats,response_delay_days,category").eq("platform", platform).ilike("chatter_name", `%${chatter_name}%`).gte("analysis_date", from.toISOString().slice(0, 10)).order("analysis_date", { ascending: false }).limit(800);
    if (error) return errorResult(error.message);
    const rows = activeNames ? (data ?? []).filter((r) => activeNames.has((r.chatter_name ?? "").trim().toLowerCase().replace(/\s+/g, "_"))) : data ?? [];
    return textResult({ count: rows.length, rows });
  }
});

// src/lib/mcp/tools/get-account-history.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var get_account_history_default = defineTool3({
  name: "get_account_history",
  title: "Account-Chronologie",
  description: "Chronologie eines Accounts/Models: welche Chatter sa\xDFen wann darauf, mit Umsatz pro Tag, Durchschnitt und bestem Tag. F\xFCr 'lief der Account fr\xFCher besser' sowie Besetzungs- und Tausch-Fragen.",
  inputSchema: {
    platform: z3.string().describe("Plattform, z.B. 'Maloum'."),
    account: z3.string().describe("Account-/Model-Name (Teilstring reicht)."),
    days: z3.number().nullable().describe("Zeitfenster in Tagen, Default 90.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ platform, account, days }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const win = Math.min(days ?? 90, 365);
    const from = /* @__PURE__ */ new Date();
    from.setDate(from.getDate() - win);
    const { data, error } = await supabaseForUser(ctx).from("chatter_history").select("analysis_date,chatter_name,account,revenue_today,open_chats,response_delay_days").eq("platform", platform).ilike("account", `%${account}%`).gte("analysis_date", from.toISOString().slice(0, 10)).order("analysis_date", { ascending: false }).limit(1500);
    if (error) return errorResult(error.message);
    const per = /* @__PURE__ */ new Map();
    for (const r of data ?? []) {
      const rev = Number(r.revenue_today) || 0;
      const e = per.get(r.chatter_name) ?? { days: 0, total: 0, best: 0, first: r.analysis_date, last: r.analysis_date };
      e.days += 1;
      e.total += rev;
      e.best = Math.max(e.best, rev);
      if (r.analysis_date < e.first) e.first = r.analysis_date;
      if (r.analysis_date > e.last) e.last = r.analysis_date;
      per.set(r.chatter_name, e);
    }
    const chatters = [...per.entries()].map(([chatter, e]) => ({
      chatter,
      days: e.days,
      total: Math.round(e.total),
      avg_per_day: Math.round(e.total / e.days * 10) / 10,
      best_day: Math.round(e.best),
      from: e.first,
      to: e.last
    })).sort((a, b) => b.avg_per_day - a.avg_per_day);
    return textResult({ chatters, rows: (data ?? []).slice(0, 300) });
  }
});

// src/lib/mcp/tools/get-top-chatters.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var get_top_chatters_default = defineTool4({
  name: "get_top_chatters",
  title: "Chatter-Ranking",
  description: "Aggregiertes Ranking aller Chatter einer Plattform \xFCber ein Zeitfenster: Gesamtumsatz, \xD8 pro Tag, bester Tag, aktueller Account und Kategorie. Guter Einstiegspunkt f\xFCr 'wer performt', 'wer ist im R\xFCckgang'. Beschr\xE4nkt auf Chatter, die im letzten Report vorkommen.",
  inputSchema: {
    platform: z4.string().describe("Plattform, z.B. 'Maloum'."),
    days: z4.number().nullable().describe("Zeitfenster in Tagen, Default 14."),
    limit: z4.number().nullable().describe("Max. Anzahl Chatter, Default 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ platform, days, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const win = Math.min(days ?? 14, 180);
    const from = /* @__PURE__ */ new Date();
    from.setDate(from.getDate() - win);
    const supabase = supabaseForUser(ctx);
    const activeNames = await loadActiveChatterNames(supabase, platform);
    const rows = [];
    for (let offset = 0; offset < 2e4; offset += 1e3) {
      const { data, error } = await supabase.from("chatter_history").select("chatter_name,analysis_date,revenue_today,mass_dms,open_chats,response_delay_days,category,account").eq("platform", platform).gte("analysis_date", from.toISOString().slice(0, 10)).order("analysis_date", { ascending: false }).range(offset, offset + 999);
      if (error) return errorResult(error.message);
      const page = activeNames ? (data ?? []).filter((r) => activeNames.has((r.chatter_name ?? "").trim().toLowerCase().replace(/\s+/g, "_"))) : data ?? [];
      rows.push(...page);
      if (!data || data.length < 1e3) break;
    }
    const per = /* @__PURE__ */ new Map();
    for (const r of rows) {
      const rev = Number(r.revenue_today) || 0;
      const e = per.get(r.chatter_name) ?? { days: 0, total: 0, best: 0, latest: r };
      e.days += 1;
      e.total += rev;
      e.best = Math.max(e.best, rev);
      if (r.analysis_date > e.latest.analysis_date) e.latest = r;
      per.set(r.chatter_name, e);
    }
    const ranked = [...per.entries()].map(([chatter, e]) => ({
      chatter,
      account: e.latest.account,
      category: e.latest.category,
      days: e.days,
      total_revenue: Math.round(e.total),
      avg_per_day: Math.round(e.total / e.days * 10) / 10,
      best_day: Math.round(e.best),
      last_open_chats: e.latest.open_chats,
      last_delay_days: e.latest.response_delay_days
    })).sort((a, b) => b.total_revenue - a.total_revenue).slice(0, Math.min(limit ?? 50, 300));
    return textResult({ platform, window_days: win, count: ranked.length, chatters: ranked });
  }
});

// src/lib/mcp/tools/read-memos.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^3.25.76";
var read_memos_default = defineTool5({
  name: "read_memos",
  title: "Memos lesen",
  description: "Liest gespeicherte Memos und Vereinbarungen zu Chattern (inkl. Fristen / Follow-up-Datum). Nutze das vor Empfehlungen zu einem Chatter, um bereits angesto\xDFene Ma\xDFnahmen nicht zu wiederholen.",
  inputSchema: {
    platform: z5.string().describe("Plattform, z.B. 'Maloum'."),
    chatter_name: z5.string().nullable().describe("Optionaler Chatter-Filter (Teilstring)."),
    status: z5.enum(["open", "resolved", "all"]).nullable().describe("Default 'open'."),
    due_only: z5.boolean().nullable().describe("Nur heute f\xE4llige oder \xFCberf\xE4llige Memos."),
    limit: z5.number().nullable().describe("Max. Anzahl, Default 30.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ platform, chatter_name, status, due_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    let q = supabaseForUser(ctx).from("chatter_memos").select("id,chatter_name,text,topic,follow_up_at,status,created_at,resolved_at").eq("platform", platform);
    if (chatter_name) q = q.ilike("chatter_name", `%${chatter_name}%`);
    const effectiveStatus = status ?? "open";
    if (effectiveStatus !== "all") q = q.eq("status", effectiveStatus);
    if (due_only) q = q.lte("follow_up_at", (/* @__PURE__ */ new Date()).toISOString());
    const { data, error } = await q.order("created_at", { ascending: false }).limit(Math.min(limit ?? 30, 100));
    if (error) return errorResult(error.message);
    return textResult({ count: data?.length ?? 0, memos: data });
  }
});

// src/lib/mcp/tools/create-memo.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z6 } from "npm:zod@^3.25.76";
var create_memo_default = defineTool6({
  name: "create_memo",
  title: "Memo anlegen",
  description: "Legt ein Memo / eine Vereinbarung f\xFCr einen Chatter an, optional mit Frist. Nutze das bei 'notier:', 'merk dir', 'gib X noch N Tage', 'erinner mich'.",
  inputSchema: {
    platform: z6.string().describe("Plattform, z.B. 'Maloum'."),
    chatter_name: z6.string().describe("Name des Chatters."),
    text: z6.string().min(1).describe("Was wurde vereinbart bzw. die Notiz."),
    follow_up_days: z6.number().nullable().describe("Tage bis zur Erinnerung, optional."),
    topic: z6.string().nullable().describe("Kurz-Tag, z.B. 'frist', 'mass_dms_low'.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ platform, chatter_name, text, follow_up_days, topic }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    let followUp = null;
    if (typeof follow_up_days === "number") {
      const d = /* @__PURE__ */ new Date();
      d.setDate(d.getDate() + follow_up_days);
      d.setHours(8, 0, 0, 0);
      followUp = d.toISOString();
    }
    const { data, error } = await supabaseForUser(ctx).from("chatter_memos").insert({
      user_id: ctx.getUserId(),
      platform,
      chatter_name,
      text,
      topic: topic ?? null,
      follow_up_at: followUp,
      status: "open"
    }).select().single();
    if (error) return errorResult(error.message);
    return textResult({ ok: true, memo: data });
  }
});

// src/lib/mcp/tools/resolve-memo.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z7 } from "npm:zod@^3.25.76";
var resolve_memo_default = defineTool7({
  name: "resolve_memo",
  title: "Memo erledigen",
  description: "Markiert ein Memo als erledigt. Nutze das, wenn der Chatter geliefert hat oder das Thema geschlossen wird.",
  inputSchema: {
    memo_id: z7.string().describe("ID des Memos (aus read_memos).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ memo_id }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const { error } = await supabaseForUser(ctx).from("chatter_memos").update({ status: "resolved", resolved_at: (/* @__PURE__ */ new Date()).toISOString() }).eq("id", memo_id);
    if (error) return errorResult(error.message);
    return textResult({ ok: true });
  }
});

// src/lib/mcp/index.ts
var projectRef = "kgtbciqqvctjrelgbdvx";
var mcp_default = defineMcp({
  name: "controlling-mcp",
  title: "Controlling Dashboard",
  version: "0.1.0",
  instructions: `Tools f\xFCr das Controlling-Dashboard einer Chatting-Agency.

Datenmodell: Chatter (Mitarbeiter) betreuen Models/Accounts auf Plattformen (z.B. "Maloum", "Brezzels"). Umsatz wird pro Chatter und Tag erfasst.

Arbeitsweise:
- F\xFCr Verzug, offene Chats und aktuelle Lage IMMER get_live_status (Echtzeit) statt Report-Daten. Verzug z\xE4hlt erst ab 3 Tagen \xE4ltestem unbeantworteten Chat.
- F\xFCr Verl\xE4ufe get_chatter_history, f\xFCr Besetzungs-/Tauschfragen get_account_history, f\xFCr Rankings get_top_chatters.
- Priorisierung bei "wen soll ich mir vornehmen": 1) historisches Uplift-Potenzial (bestes \u20AC/Tag fr\xFCher vs. heute), 2) Verzug, 3) offene Chats, 4) aktueller Umsatz (0 \u20AC-F\xE4lle zuerst).
- Antworte knapp, faktenbasiert, mit Zahlen in \u20AC und konkreter Handlungsempfehlung. Nie "s\xE4uft ab" \u2014 sag "im R\xFCckgang".`,
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_live_status_default, get_chatter_history_default, get_account_history_default, get_top_chatters_default, read_memos_default, create_memo_default, resolve_memo_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
